version: '3'
services:
  app-group-1:
    build: .
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "9101-9200:80"
  app-group-2:
    build: .
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "9090-9100:80"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-group-1
      - app-group-2
    ports:
      - "80:80"